### ISSUE TITLE
求数据，求数据

### ISSUE THREAD

**Issue by sorrymyfault** [wuhuanyan/buy_pig_plan_python#1]
大哥你没有留下联系方式，不知道该如何联系你。数据不知道该去哪里爬

如果方便的话，引用配置文件的教程方式能否再详细一点，毕竟装个oracle太麻烦了，很容易出问题。谢谢了

我的邮箱是redmine_lianai@163.com

**Comment by wuhuanyan** [comment]
数据是通过下方网站爬取的：[离线宝免费电话回呼](http://lxbjs.baidu.com/cb/url/show?f=55&id=100)，在后面更改ID参数`(ID大约去到13万)`，例如：
`url = f'http://lxbjs.baidu.com/cb/url/show?f=55&id={id_}'`
你可以参考`lixianbao/main.py`更改你采集网站脚本，把入库代码更改写入到本地文件中。

**Comment by wuhuanyan** [comment]
这边提供了网站数据[lixianbao/web_info.sql](https://github.com/wuhuanyan/buy_pig_plan_python/blob/master/lixianbao/web_info.sql)你提取整理一下就可以用。
另外我已更新我的联系方式，如果有不明白的，可以继续联系我。

**Comment by sorrymyfault** [comment]
感激不尽！！！
